version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 750
    type:
      - directory
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 640
    type:
      - file
