---
version: 0
os: linux
files:
  - source: /
    destination: /var/www/html
permissions:
#Permissions for directories
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 750
    type:
      - directory
      
#Permissions for files
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
    mode: 640
    type:
      - file
